[package]
name = "get-mastodon-history"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive", "env"] }
dotenvy = "0.15.7"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.132"
